// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6uji58gp2hjfS5vcmUNX3xQ5PBZC6bU',
    appId: '1:825265145858:web:e55029e0ddaaf9d97fbf1b',
    messagingSenderId: '825265145858',
    projectId: 'eventdb-3c41d',
    authDomain: 'eventdb-3c41d.firebaseapp.com',
    storageBucket: 'eventdb-3c41d.firebasestorage.app',
    measurementId: 'G-TC47N3XKDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfi-Urt4yvw18CFODCEUkB5FIUsOjFbM',
    appId: '1:825265145858:android:3f3de518760f93a87fbf1b',
    messagingSenderId: '825265145858',
    projectId: 'eventdb-3c41d',
    storageBucket: 'eventdb-3c41d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7aHh3SG-i5OtSyqIRzf7PLPZVsZ7Rb04',
    appId: '1:825265145858:ios:d0fd71fba86641c07fbf1b',
    messagingSenderId: '825265145858',
    projectId: 'eventdb-3c41d',
    storageBucket: 'eventdb-3c41d.firebasestorage.app',
    iosBundleId: 'com.example.withfbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7aHh3SG-i5OtSyqIRzf7PLPZVsZ7Rb04',
    appId: '1:825265145858:ios:d0fd71fba86641c07fbf1b',
    messagingSenderId: '825265145858',
    projectId: 'eventdb-3c41d',
    storageBucket: 'eventdb-3c41d.firebasestorage.app',
    iosBundleId: 'com.example.withfbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV6uji58gp2hjfS5vcmUNX3xQ5PBZC6bU',
    appId: '1:825265145858:web:9c43feaab72d4b617fbf1b',
    messagingSenderId: '825265145858',
    projectId: 'eventdb-3c41d',
    authDomain: 'eventdb-3c41d.firebaseapp.com',
    storageBucket: 'eventdb-3c41d.firebasestorage.app',
    measurementId: 'G-X34ZFCMJKP',
  );
}
